- name: install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Create dnsmasq config
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

# from https://www.server-world.info/en/note?os=Ubuntu_20.04&p=dnsmasq&f=1
- name: Link resolve.conf
  file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/resolv.conf
    state: link

- name: Start dnsmasq
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - dnsmasq
    - systemd-resolved

- name: Setup network config
  template:
    src: "{{ item.source }}"
    dest: "/etc/netplan/{{ item.dest }}"
  with_items:
    - { dest: '01-netcfg.yaml', source: 'netplancfg-eth0.yml.j2' }
    - { dest: '50-vagrant.yaml', source: 'netplancfg-eth1.yml.j2' }
  register: netcfg_changes 

- name: Apply netcfg
  shell: netplan apply
  when: netcfg_changes.changed  
